pipeline {
  agent {
    label 'a001'
  }

  stages {
    stage('Build for production') {
      steps {
        checkout scm
        sh 'ls -lah'
	sh 'pwd'
	//git url: 'https://github.com/jtokarski/frontdev1.git'
        echo 'Building Application'
      }
    }

    stage('End-to-end test') {
      steps {
        echo 'Running Cypress'
      }
    }
  }
}

